name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7.17.1

    - name: Checkout
      uses: actions/checkout@v2
      with:
        node-version: 18.x

    - name: Install
      run: |
        pnpm install
      env:
        CI: true

    - name: Build
      run: |
        pnpm run --if-present build
      env:
        CI: true

    - name: Test
      run: |
        pnpm run --if-present ci
      env:
        CI: true

    - name: Build Docs
      run: |
        pnpm run --if-present build-docs
      env:
        CI: true

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: dist/ngx-datatable
      if: ${{ github.ref == 'refs/heads/master' }}
